version: '3.9'

services:
  pgdb:
    restart: "no"
    container_name: "mealprep_pg"
    image: postgres:13
    environment:
      - POSTGRES_USER=${MEALPREPDB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MEALPREPDB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${MEALPREPDB_POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mealprepdb"]
      interval: 2s
      timeout: 3s
      retries: 10
    expose:
      - "5432"
    ports:
      - "5454:5432" # for debugging 
    shm_size: 1g

  api:
    restart: "no"
    container_name: "mealprepdb_api"
    image: mealprepdb:dev
    environment:
      - WAIT_HOSTS=pgdb:5432
      - MEALPREPDB_POSTGRES_USER=${MEALPREPDB_POSTGRES_USER}
      - MEALPREPDB_POSTGRES_PASSWORD=${MEALPREPDB_POSTGRES_PASSWORD}
      - MEALPREPDB_POSTGRES_HOST=${MEALPREPDB_POSTGRES_HOST}
      - MEALPREPDB_POSTGRES_PORT=${MEALPREPDB_POSTGRES_PORT}
      - MEALPREPDB_POSTGRES_DB=${MEALPREPDB_POSTGRES_DB}
      - MEALPREPDB_POSTGRES_TEST_DB=${MEALPREPDB_POSTGRES_TEST_DB}
      - MEALPREPDB_ENVIRONMENT=${MEALPREPDB_ENVIRONMENT}
      - MEALPREPDB_AUTH0_DOMAIN=${MEALPREPDB_AUTH0_DOMAIN}
      - MEALPREPDB_AUTH0_AUDIENCE=${MEALPREPDB_AUTH0_AUDIENCE}
      - MEALPREPDB_AUTH0_CLIENT_ID=${MEALPREPDB_AUTH0_CLIENT_ID}
      - MEALPREPDB_AUTH0_SECRET=${MEALPREPDB_AUTH0_SECRET}
      - MEALPREPDB_DB_ENGINE_MAX_OVERFLOW=${MEALPREPDB_DB_ENGINE_MAX_OVERFLOW}
      - MEALPREPDB_DB_ENGINE_POOL_SIZE=${MEALPREPDB_DB_ENGINE_POOL_SIZE}
      - MEALPREPDB_LIVE_TEST_URL=${MEALPREPDB_LIVE_TEST_URL}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "../wait && uvicorn --host 0.0.0.0 --port 8080 --log-level debug --reload mealprepdb.api.main:app"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      pgdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/"]
      #wait for this i guess https://github.com/moby/moby/pull/46646
      # https://github.com/moby/moby/issues/45897..
      start_period: 0s
      # start-interval: 5s #docker engine needs to be 25 for this to work
      interval: 10s
      timeout: 10s
      retries: 10
    
  frontend: 
    restart: "always"
    container_name: "mealprepdb_frontend"
    image: mealprepdb:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "gunicorn mealprepdb.frontend.app:server -b 0.0.0.0:8081 --log-level debug --reload"
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    depends_on:
      api:
        condition: service_healthy

volumes:
  pgdata:
  cache:
